FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "senoss_core.api.extended_server_full:app", "--host", "0.0.0.0", "--port", "8000"]
